name: do_an_at140225
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0
  intl: ^0.16.1
  flutter_bloc: ^4.0.0
  loading: ^1.0.2
  flutter_screenutil: ^1.1.0
  flutter_hooks: ^0.9.0
  mqtt_client: ^6.2.0
  equatable: ^1.1.1
  get_it: ^4.0.1
  font_awesome_flutter: ^8.8.1
  toast: ^0.1.5
  shared_preferences: ^0.5.12
  route_transitions: ^1.0.2
  encrypt: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/avatar.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 700
    - family: Air
      fonts:
        - asset: assets/icons/air.ttf
    - family: LightHome
      fonts:
        - asset: assets/icons/light_home.ttf
    - family: Temp
      fonts:
        - asset: assets/icons/temp.ttf
    - family: Water
      fonts:
        - asset: assets/icons/water.ttf
    - family: OneWater
      fonts:
        - asset: assets/icons/one_water.ttf