name: attendance_app
description: Attendance application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0
  intl: ^0.16.1
  flutter_bloc: ^4.0.0
  loading: ^1.0.2
  flutter_screenutil: ^1.1.0
  flutter_hooks: ^0.9.0
  mqtt_client: ^6.2.0
  equatable: ^1.1.1
  get_it: ^4.0.1
  countdown: ^0.1.0
  # csv
  #csv: ^4.0.3
  # to get address storage file
  path_provider: ^1.6.8  # todo: config ios
  # use to storage permission
  permission_handler: ^5.0.0+hotfix.9 # todo: config ios
  # export to excel file
  excel: ^1.0.3  # todo: config ios
  # to use `join` file
  path: ^1.6.4  # todo: config ios
  #icon
  font_awesome_flutter: ^8.8.1
  toast: ^0.1.5
  #open file excel
  open_file: ^3.0.1  # todo: config ios
  shared_preferences: ^0.5.12
  route_transitions: ^1.0.2
  encrypt: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/avatar.png
    - assets/images/cover.png
    - assets/images/profile/dao_cam_anh.JPG
    - assets/images/profile/ngo_quang_huy.JPG
    - assets/images/profile/nguyen_minh_quang.JPG
    - assets/images/profile/vu_hoang_son.JPG
    - assets/images/profile/ta_minh_son.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 700
    - family: Air
      fonts:
        - asset: assets/icons/air.ttf
    - family: LightHome
      fonts:
        - asset: assets/icons/light_home.ttf
    - family: Temp
      fonts:
        - asset: assets/icons/temp.ttf
    - family: Water
      fonts:
        - asset: assets/icons/water.ttf
    - family: OneWater
      fonts:
        - asset: assets/icons/one_water.ttf
  #  - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
